# Generated by Django 4.0.3 on 2022-05-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arctel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='body',
        ),
    ]
