# Generated by Django 4.0.3 on 2022-05-25 13:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('arctel', '0003_news_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='Item'))), ('image', wagtail.images.blocks.ImageChooserBlock())], default=None, use_json_field=None),
            preserve_default=False,
        ),
    ]
