# Generated by Django 4.0.3 on 2022-05-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arctel', '0004_menuitem_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationoffer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formationoffer',
            name='text',
        ),
    ]
