# Generated by Django 4.0.3 on 2022-05-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arctel', '0006_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
